// Command reset генерирует методы Reset() для структур с комментарием // generate:reset.
//
// Использование:
//
//	go run cmd/reset/main.go ./internal/...
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"
)

type structInfo struct {
	PkgName string
	Name    string
	Fields  []fieldInfo
	File    string
}

type fieldInfo struct {
	Name string
	Type string
}

type packageInfo struct {
	PkgName string
	Dir     string
	Structs []structInfo
}

func main() {

	structs := findResetStructs(".")

	if len(structs) == 0 {
		fmt.Println("Нет структур с // generate:reset")
		return
	}

	packages := make(map[string]packageInfo)

	for _, s := range structs {
		dir := filepath.Dir(s.File)

		pkg := packages[dir]
		if pkg.PkgName == "" {
			pkg.PkgName = s.PkgName
			pkg.Dir = dir
		}

		pkg.Structs = append(pkg.Structs, s)

		packages[dir] = pkg
	}

	for _, pkg := range packages {
		generateResetPackage(pkg)
	}

	fmt.Println("Генерация завершена")
}

func findResetStructs(root string) []structInfo {
	var result []structInfo

	err := filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}

		if d.IsDir() {
			name := d.Name()
			if name != "." && name != ".." && strings.HasPrefix(name, ".") {
				return filepath.SkipDir
			}
			if name == "vendor" || name == "cmd" || name == ".git" {
				return filepath.SkipDir
			}
			return nil
		}

		if !strings.HasSuffix(path, ".go") ||
			strings.HasSuffix(path, "_test.go") ||
			strings.HasSuffix(path, "_generated.go") ||
			strings.HasSuffix(path, ".gen.go") {
			return nil
		}

		fset := token.NewFileSet()
		file, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if err != nil {
			log.Panicln(err)
			return nil
		}
		ast.Inspect(file, func(n ast.Node) bool {
			decl, ok := n.(*ast.GenDecl)
			if !ok || decl.Tok != token.TYPE || decl.Doc == nil {
				return true
			}

			hasReset := false
			for _, comment := range decl.Doc.List {
				if strings.Contains(comment.Text, "generate:reset") {
					hasReset = true
					break
				}
			}
			if !hasReset {
				return true
			}

			for _, spec := range decl.Specs {
				if typeSpec, ok := spec.(*ast.TypeSpec); ok {
					if structType, ok := typeSpec.Type.(*ast.StructType); ok {
						fields := extractFields(structType)
						result = append(result, structInfo{
							PkgName: file.Name.Name,
							Name:    typeSpec.Name.Name,
							Fields:  fields,
							File:    path,
						})
					}
				}
			}

			return true
		})

		return nil
	})

	if err != nil {
		log.Fatal(err)
	}

	return result
}

func extractFields(structType *ast.StructType) []fieldInfo {
	var fields []fieldInfo
	for _, field := range structType.Fields.List {
		if field.Names == nil {
			continue
		}

		for _, name := range field.Names {
			fields = append(fields, fieldInfo{
				Name: name.Name,
				Type: exprToString(field.Type),
			})
		}
	}
	return fields
}

func exprToString(expr ast.Expr) string {
	switch e := expr.(type) {
	case *ast.Ident:
		return e.Name
	case *ast.StarExpr:
		return "*" + exprToString(e.X)
	case *ast.ArrayType:
		if e.Len == nil {
			return "[]" + exprToString(e.Elt)
		}
		return fmt.Sprintf("[%s]%s", exprToString(e.Len), exprToString(e.Elt))
	case *ast.MapType:
		return fmt.Sprintf("map[%s]%s", exprToString(e.Key), exprToString(e.Value))
	case *ast.SelectorExpr:
		return fmt.Sprintf("%s.%s", exprToString(e.X), e.Sel.Name)
	default:
		return "interface{}"
	}
}

func generateResetPackage(pkg packageInfo) {
	sort.Slice(pkg.Structs, func(i, j int) bool {
		return pkg.Structs[i].Name < pkg.Structs[j].Name
	})

	tmpl := template.Must(template.New("reset").Parse(
		`// Code generated by reset; DO NOT EDIT.

package {{.PkgName}}

{{range .Structs}}// Reset сбрасывает все поля структуры {{.Name}} к начальным значениям.
func (r *{{.Name}}) Reset() {
	if x == nil {
		return
	}
{{range .Fields}}	r.{{.Name}} = {{.ZeroValue}}
{{end}}}
{{end}}`,
	))

	type tmplField struct {
		Name      string
		ZeroValue string
	}
	type tmplStruct struct {
		Name   string
		Fields []tmplField
	}
	type tmplData struct {
		PkgName string
		Structs []tmplStruct
	}

	data := tmplData{
		PkgName: pkg.PkgName,
		Structs: make([]tmplStruct, len(pkg.Structs)),
	}

	for i, s := range pkg.Structs {
		fields := make([]tmplField, len(s.Fields))
		for j, f := range s.Fields {
			fields[j] = tmplField{
				Name:      f.Name,
				ZeroValue: zeroValueForType(f.Type),
			}
		}
		data.Structs[i] = tmplStruct{
			Name:   s.Name,
			Fields: fields,
		}
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		log.Fatal(err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatalf("Ошибка: %v", err)
	}

	genFile := filepath.Join(pkg.Dir, "reset.gen.go")
	if err := os.WriteFile(genFile, formatted, 0644); err != nil {
		log.Fatal(err)
	}

}

func zeroValueForType(t string) string {
	t = strings.TrimSpace(t)

	switch t {
	case "time.Duration":
		return "0"
	}

	switch t {
	case "string":
		return `""`
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"rune", "byte":
		return "0"
	case "float32", "float64":
		return "0.0"
	case "bool":
		return "false"
	}

	if strings.HasPrefix(t, "[]") {
		return "nil"
	}
	if strings.HasPrefix(t, "map[") {
		return "nil"
	}
	if strings.HasPrefix(t, "*") {
		return "nil"
	}
	if t == "interface{}" || t == "error" {
		return "nil"
	}

	return t + "{}"
}
